/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ActivityEntry = IDL.Record({
  'appSite' : IDL.Text,
  'childId' : IDL.Principal,
  'durationMinutes' : IDL.Nat,
  'notes' : IDL.Text,
  'timestamp' : Time,
});
export const LocationEntry = IDL.Record({
  'latitude' : IDL.Float64,
  'childId' : IDL.Principal,
  'longitude' : IDL.Float64,
  'timestamp' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const AppRole = IDL.Variant({
  'admin' : IDL.Null,
  'child' : IDL.Null,
  'parent' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : AppRole });
export const ActionType = IDL.Variant({
  'pairingCreated' : IDL.Null,
  'filterChanged' : IDL.Null,
  'accountDisabled' : IDL.Null,
  'scheduleChanged' : IDL.Null,
});
export const PairingDetails = IDL.Record({
  'child' : IDL.Principal,
  'parent' : IDL.Principal,
});
export const ContentCategory = IDL.Record({
  'name' : IDL.Text,
  'enabled' : IDL.Bool,
});
export const ContentFilterConfig = IDL.Record({
  'categories' : IDL.Vec(ContentCategory),
  'blocklist' : IDL.Vec(IDL.Text),
  'allowlist' : IDL.Vec(IDL.Text),
});
export const FilterChangeDetails = IDL.Record({
  'child' : IDL.Principal,
  'newConfig' : ContentFilterConfig,
});
export const AccountDisabledDetails = IDL.Record({
  'account' : IDL.Principal,
  'reason' : IDL.Text,
});
export const DayTimeWindow = IDL.Record({
  'endHour' : IDL.Nat,
  'dayOfWeek' : IDL.Nat,
  'startHour' : IDL.Nat,
});
export const ScheduleConfig = IDL.Record({
  'allowedHours' : IDL.Vec(DayTimeWindow),
  'dailyLimitMinutes' : IDL.Nat,
});
export const ScheduleChangeDetails = IDL.Record({
  'child' : IDL.Principal,
  'newConfig' : ScheduleConfig,
});
export const AuditLogDetails = IDL.Variant({
  'pairingCreated' : PairingDetails,
  'filterChanged' : FilterChangeDetails,
  'accountDisabled' : AccountDisabledDetails,
  'scheduleChanged' : ScheduleChangeDetails,
});
export const AuditLogEntry = IDL.Record({
  'action' : ActionType,
  'timestamp' : Time,
  'details' : AuditLogDetails,
  'executor' : IDL.Principal,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addActivity' : IDL.Func([ActivityEntry], [], []),
  'addLocation' : IDL.Func([LocationEntry], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'disableAccount' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'enableAccount' : IDL.Func([IDL.Principal], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getActivities' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ActivityEntry)],
      ['query'],
    ),
  'getAggregatedMetrics' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalParents' : IDL.Nat,
          'totalChildren' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalPairings' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAuditLog' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AuditLogEntry)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContentFilter' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ContentFilterConfig)],
      ['query'],
    ),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getLiveLocationSharingStatus' : IDL.Func(
      [IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'getLocations' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(LocationEntry)],
      ['query'],
    ),
  'getMyChildren' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getMyParent' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getParentChildLinks' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Principal)))],
      ['query'],
    ),
  'getSchedule' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ScheduleConfig)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAccountDisabled' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdminPassword' : IDL.Func([IDL.Text], [], []),
  'setLiveLocationSharing' : IDL.Func([IDL.Bool], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'updateContentFilter' : IDL.Func(
      [IDL.Principal, ContentFilterConfig],
      [],
      [],
    ),
  'updateSchedule' : IDL.Func([IDL.Principal, ScheduleConfig], [], []),
  'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ActivityEntry = IDL.Record({
    'appSite' : IDL.Text,
    'childId' : IDL.Principal,
    'durationMinutes' : IDL.Nat,
    'notes' : IDL.Text,
    'timestamp' : Time,
  });
  const LocationEntry = IDL.Record({
    'latitude' : IDL.Float64,
    'childId' : IDL.Principal,
    'longitude' : IDL.Float64,
    'timestamp' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const AppRole = IDL.Variant({
    'admin' : IDL.Null,
    'child' : IDL.Null,
    'parent' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : AppRole });
  const ActionType = IDL.Variant({
    'pairingCreated' : IDL.Null,
    'filterChanged' : IDL.Null,
    'accountDisabled' : IDL.Null,
    'scheduleChanged' : IDL.Null,
  });
  const PairingDetails = IDL.Record({
    'child' : IDL.Principal,
    'parent' : IDL.Principal,
  });
  const ContentCategory = IDL.Record({
    'name' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  const ContentFilterConfig = IDL.Record({
    'categories' : IDL.Vec(ContentCategory),
    'blocklist' : IDL.Vec(IDL.Text),
    'allowlist' : IDL.Vec(IDL.Text),
  });
  const FilterChangeDetails = IDL.Record({
    'child' : IDL.Principal,
    'newConfig' : ContentFilterConfig,
  });
  const AccountDisabledDetails = IDL.Record({
    'account' : IDL.Principal,
    'reason' : IDL.Text,
  });
  const DayTimeWindow = IDL.Record({
    'endHour' : IDL.Nat,
    'dayOfWeek' : IDL.Nat,
    'startHour' : IDL.Nat,
  });
  const ScheduleConfig = IDL.Record({
    'allowedHours' : IDL.Vec(DayTimeWindow),
    'dailyLimitMinutes' : IDL.Nat,
  });
  const ScheduleChangeDetails = IDL.Record({
    'child' : IDL.Principal,
    'newConfig' : ScheduleConfig,
  });
  const AuditLogDetails = IDL.Variant({
    'pairingCreated' : PairingDetails,
    'filterChanged' : FilterChangeDetails,
    'accountDisabled' : AccountDisabledDetails,
    'scheduleChanged' : ScheduleChangeDetails,
  });
  const AuditLogEntry = IDL.Record({
    'action' : ActionType,
    'timestamp' : Time,
    'details' : AuditLogDetails,
    'executor' : IDL.Principal,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addActivity' : IDL.Func([ActivityEntry], [], []),
    'addLocation' : IDL.Func([LocationEntry], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'disableAccount' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'enableAccount' : IDL.Func([IDL.Principal], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getActivities' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ActivityEntry)],
        ['query'],
      ),
    'getAggregatedMetrics' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalParents' : IDL.Nat,
            'totalChildren' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalPairings' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAuditLog' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AuditLogEntry)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContentFilter' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ContentFilterConfig)],
        ['query'],
      ),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getLiveLocationSharingStatus' : IDL.Func(
        [IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'getLocations' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(LocationEntry)],
        ['query'],
      ),
    'getMyChildren' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getMyParent' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getParentChildLinks' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Principal)))],
        ['query'],
      ),
    'getSchedule' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ScheduleConfig)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAccountDisabled' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdminPassword' : IDL.Func([IDL.Text], [], []),
    'setLiveLocationSharing' : IDL.Func([IDL.Bool], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'updateContentFilter' : IDL.Func(
        [IDL.Principal, ContentFilterConfig],
        [],
        [],
      ),
    'updateSchedule' : IDL.Func([IDL.Principal, ScheduleConfig], [], []),
    'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };