/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountDisabledDetails {
  'account' : Principal,
  'reason' : string,
}
export type ActionType = { 'pairingCreated' : null } |
  { 'filterChanged' : null } |
  { 'accountDisabled' : null } |
  { 'scheduleChanged' : null };
export interface ActivityEntry {
  'appSite' : string,
  'childId' : Principal,
  'durationMinutes' : bigint,
  'notes' : string,
  'timestamp' : Time,
}
export type AppRole = { 'admin' : null } |
  { 'child' : null } |
  { 'parent' : null };
export type AuditLogDetails = { 'pairingCreated' : PairingDetails } |
  { 'filterChanged' : FilterChangeDetails } |
  { 'accountDisabled' : AccountDisabledDetails } |
  { 'scheduleChanged' : ScheduleChangeDetails };
export interface AuditLogEntry {
  'action' : ActionType,
  'timestamp' : Time,
  'details' : AuditLogDetails,
  'executor' : Principal,
}
export interface ContentCategory { 'name' : string, 'enabled' : boolean }
export interface ContentFilterConfig {
  'categories' : Array<ContentCategory>,
  'blocklist' : Array<string>,
  'allowlist' : Array<string>,
}
export interface DayTimeWindow {
  'endHour' : bigint,
  'dayOfWeek' : bigint,
  'startHour' : bigint,
}
export interface FilterChangeDetails {
  'child' : Principal,
  'newConfig' : ContentFilterConfig,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface LocationEntry {
  'latitude' : number,
  'childId' : Principal,
  'longitude' : number,
  'timestamp' : Time,
}
export interface PairingDetails { 'child' : Principal, 'parent' : Principal }
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface ScheduleChangeDetails {
  'child' : Principal,
  'newConfig' : ScheduleConfig,
}
export interface ScheduleConfig {
  'allowedHours' : Array<DayTimeWindow>,
  'dailyLimitMinutes' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : AppRole }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addActivity' : ActorMethod<[ActivityEntry], undefined>,
  'addLocation' : ActorMethod<[LocationEntry], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'disableAccount' : ActorMethod<[Principal, string], undefined>,
  'enableAccount' : ActorMethod<[Principal], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getActivities' : ActorMethod<[Principal], Array<ActivityEntry>>,
  'getAggregatedMetrics' : ActorMethod<
    [],
    {
      'totalParents' : bigint,
      'totalChildren' : bigint,
      'totalUsers' : bigint,
      'totalPairings' : bigint,
    }
  >,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAuditLog' : ActorMethod<[Principal], Array<AuditLogEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContentFilter' : ActorMethod<[Principal], [] | [ContentFilterConfig]>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getLocations' : ActorMethod<[Principal], Array<LocationEntry>>,
  'getMyChildren' : ActorMethod<[], Array<Principal>>,
  'getMyParent' : ActorMethod<[], [] | [Principal]>,
  'getParentChildLinks' : ActorMethod<[], Array<[Principal, Array<Principal>]>>,
  'getSchedule' : ActorMethod<[Principal], [] | [ScheduleConfig]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAccountDisabled' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdminPassword' : ActorMethod<[string], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'updateContentFilter' : ActorMethod<
    [Principal, ContentFilterConfig],
    undefined
  >,
  'updateSchedule' : ActorMethod<[Principal, ScheduleConfig], undefined>,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];