/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PairWithParentResult = IDL.Variant({
  'alreadyUsed' : IDL.Null,
  'parentIdNotProvided' : IDL.Null,
  'phoneVerificationExpired' : IDL.Null,
  'notAChild' : IDL.Null,
  'codeExpired' : IDL.Null,
  'sameFamily' : IDL.Null,
  'unexpectedError' : IDL.Null,
  'phoneVerificationInitiated' : IDL.Null,
  'parentNotFound' : IDL.Null,
  'alreadyPaired' : IDL.Null,
  'parentNotParent' : IDL.Null,
  'pendingLinkRequest' : IDL.Null,
  'invalidCode' : IDL.Null,
  'phoneVerificationSuccess' : IDL.Null,
  'success' : IDL.Null,
  'phoneVerificationFailed' : IDL.Null,
  'phoneNumberAlreadyLinked' : IDL.Null,
});
export const Time = IDL.Int;
export const ActivityEntry = IDL.Record({
  'appSite' : IDL.Text,
  'childId' : IDL.Principal,
  'durationMinutes' : IDL.Nat,
  'notes' : IDL.Text,
  'timestamp' : Time,
});
export const LocationEntry = IDL.Record({
  'latitude' : IDL.Float64,
  'childId' : IDL.Principal,
  'longitude' : IDL.Float64,
  'timestamp' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminDashboardMetrics = IDL.Record({
  'totalUsersEverLoggedIn' : IDL.Nat,
  'totalContentFiltersConfigured' : IDL.Nat,
  'totalSchedulesConfigured' : IDL.Nat,
  'activeSessionsEstimate' : IDL.Nat,
  'totalAdmins' : IDL.Nat,
  'totalPendingPairings' : IDL.Nat,
  'totalDisabledAccounts' : IDL.Nat,
  'totalParents' : IDL.Nat,
  'totalChildren' : IDL.Nat,
  'totalParentChildLinks' : IDL.Nat,
});
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const ActionType = IDL.Variant({
  'pendingRequestInitiated' : IDL.Null,
  'phonePairingInitiated' : IDL.Null,
  'pendingRequestCompleted' : IDL.Null,
  'phonePairingCompleted' : IDL.Null,
  'pairingCreated' : IDL.Null,
  'accountDeleted' : IDL.Null,
  'filterChanged' : IDL.Null,
  'accountDisabled' : IDL.Null,
  'scheduleChanged' : IDL.Null,
});
export const PendingRequestInitiatedDetails = IDL.Record({
  'child' : IDL.Principal,
  'parent' : IDL.Principal,
});
export const PhonePairingInitiatedDetails = IDL.Record({
  'phoneNumber' : IDL.Text,
  'parentId' : IDL.Principal,
});
export const PendingRequestCompletedDetails = IDL.Record({
  'childPrincipal' : IDL.Principal,
  'childName' : IDL.Text,
  'successful' : IDL.Bool,
  'parent' : IDL.Principal,
});
export const PhonePairingCompletedDetails = IDL.Record({
  'childId' : IDL.Principal,
  'parentId' : IDL.Principal,
});
export const PairingDetails = IDL.Record({
  'child' : IDL.Principal,
  'parent' : IDL.Principal,
});
export const AppRole = IDL.Variant({
  'admin' : IDL.Null,
  'child' : IDL.Null,
  'parent' : IDL.Null,
});
export const AccountDeletedDetails = IDL.Record({
  'role' : AppRole,
  'account' : IDL.Principal,
});
export const ContentCategory = IDL.Record({
  'name' : IDL.Text,
  'enabled' : IDL.Bool,
});
export const ContentFilterConfig = IDL.Record({
  'categories' : IDL.Vec(ContentCategory),
  'blocklist' : IDL.Vec(IDL.Text),
  'allowlist' : IDL.Vec(IDL.Text),
});
export const FilterChangeDetails = IDL.Record({
  'child' : IDL.Principal,
  'newConfig' : ContentFilterConfig,
});
export const AccountDisabledDetails = IDL.Record({
  'account' : IDL.Principal,
  'reason' : IDL.Text,
});
export const DayTimeWindow = IDL.Record({
  'endHour' : IDL.Nat,
  'dayOfWeek' : IDL.Nat,
  'startHour' : IDL.Nat,
});
export const ScheduleConfig = IDL.Record({
  'allowedHours' : IDL.Vec(DayTimeWindow),
  'dailyLimitMinutes' : IDL.Nat,
});
export const ScheduleChangeDetails = IDL.Record({
  'child' : IDL.Principal,
  'newConfig' : ScheduleConfig,
});
export const AuditLogDetails = IDL.Variant({
  'pendingRequestInitiated' : PendingRequestInitiatedDetails,
  'phonePairingInitiated' : PhonePairingInitiatedDetails,
  'pendingRequestCompleted' : PendingRequestCompletedDetails,
  'phonePairingCompleted' : PhonePairingCompletedDetails,
  'pairingCreated' : PairingDetails,
  'accountDeleted' : AccountDeletedDetails,
  'filterChanged' : FilterChangeDetails,
  'accountDisabled' : AccountDisabledDetails,
  'scheduleChanged' : ScheduleChangeDetails,
});
export const AuditLogEntry = IDL.Record({
  'action' : ActionType,
  'timestamp' : Time,
  'details' : AuditLogDetails,
  'executor' : IDL.Principal,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : AppRole,
  'photo' : IDL.Opt(ExternalBlob),
  'phoneNumber' : IDL.Opt(IDL.Text),
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const PendingPairingRequest = IDL.Record({
  'id' : IDL.Nat,
  'pending' : IDL.Bool,
  'child' : IDL.Principal,
  'parent' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptPendingPairing' : IDL.Func([IDL.Nat], [PairWithParentResult], []),
  'addActivity' : IDL.Func([ActivityEntry], [], []),
  'addAllowlistedAdmin' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'addAllowlistedAdminPrincipal' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'addLocation' : IDL.Func([LocationEntry], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteCallerAccount' : IDL.Func([], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'generatePairingCode' : IDL.Func([], [IDL.Opt(IDL.Text)], []),
  'getActivities' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ActivityEntry)],
      ['query'],
    ),
  'getAdminDashboardMetrics' : IDL.Func([], [AdminDashboardMetrics], ['query']),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getAllowlistedAdminPrincipals' : IDL.Func(
      [],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getAuditLog' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AuditLogEntry)],
      ['query'],
    ),
  'getCallerProfilePhoto' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContentFilter' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ContentFilterConfig)],
      ['query'],
    ),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getLiveLocationSharingStatus' : IDL.Func(
      [IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'getLocations' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(LocationEntry)],
      ['query'],
    ),
  'getMyChildren' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getMyParent' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getPendingPairingRequests' : IDL.Func(
      [],
      [IDL.Vec(PendingPairingRequest)],
      ['query'],
    ),
  'getSchedule' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ScheduleConfig)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAllowlistedAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPrincipalAllowlistedAdmin' : IDL.Func(
      [IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'pairWithParent' : IDL.Func([IDL.Text], [PairWithParentResult], []),
  'recordHeartbeat' : IDL.Func([], [], []),
  'removeAllowlistedAdminPrincipal' : IDL.Func(
      [IDL.Text, IDL.Principal],
      [],
      [],
    ),
  'requestPairingWithParent' : IDL.Func(
      [IDL.Principal],
      [PairWithParentResult],
      [],
    ),
  'revokeAllowlistedAdmin' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProfilePhoto' : IDL.Func([ExternalBlob], [], []),
  'setLiveLocationSharing' : IDL.Func([IDL.Bool], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'updateContentFilter' : IDL.Func(
      [IDL.Principal, ContentFilterConfig],
      [],
      [],
    ),
  'updateSchedule' : IDL.Func([IDL.Principal, ScheduleConfig], [], []),
  'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PairWithParentResult = IDL.Variant({
    'alreadyUsed' : IDL.Null,
    'parentIdNotProvided' : IDL.Null,
    'phoneVerificationExpired' : IDL.Null,
    'notAChild' : IDL.Null,
    'codeExpired' : IDL.Null,
    'sameFamily' : IDL.Null,
    'unexpectedError' : IDL.Null,
    'phoneVerificationInitiated' : IDL.Null,
    'parentNotFound' : IDL.Null,
    'alreadyPaired' : IDL.Null,
    'parentNotParent' : IDL.Null,
    'pendingLinkRequest' : IDL.Null,
    'invalidCode' : IDL.Null,
    'phoneVerificationSuccess' : IDL.Null,
    'success' : IDL.Null,
    'phoneVerificationFailed' : IDL.Null,
    'phoneNumberAlreadyLinked' : IDL.Null,
  });
  const Time = IDL.Int;
  const ActivityEntry = IDL.Record({
    'appSite' : IDL.Text,
    'childId' : IDL.Principal,
    'durationMinutes' : IDL.Nat,
    'notes' : IDL.Text,
    'timestamp' : Time,
  });
  const LocationEntry = IDL.Record({
    'latitude' : IDL.Float64,
    'childId' : IDL.Principal,
    'longitude' : IDL.Float64,
    'timestamp' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminDashboardMetrics = IDL.Record({
    'totalUsersEverLoggedIn' : IDL.Nat,
    'totalContentFiltersConfigured' : IDL.Nat,
    'totalSchedulesConfigured' : IDL.Nat,
    'activeSessionsEstimate' : IDL.Nat,
    'totalAdmins' : IDL.Nat,
    'totalPendingPairings' : IDL.Nat,
    'totalDisabledAccounts' : IDL.Nat,
    'totalParents' : IDL.Nat,
    'totalChildren' : IDL.Nat,
    'totalParentChildLinks' : IDL.Nat,
  });
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const ActionType = IDL.Variant({
    'pendingRequestInitiated' : IDL.Null,
    'phonePairingInitiated' : IDL.Null,
    'pendingRequestCompleted' : IDL.Null,
    'phonePairingCompleted' : IDL.Null,
    'pairingCreated' : IDL.Null,
    'accountDeleted' : IDL.Null,
    'filterChanged' : IDL.Null,
    'accountDisabled' : IDL.Null,
    'scheduleChanged' : IDL.Null,
  });
  const PendingRequestInitiatedDetails = IDL.Record({
    'child' : IDL.Principal,
    'parent' : IDL.Principal,
  });
  const PhonePairingInitiatedDetails = IDL.Record({
    'phoneNumber' : IDL.Text,
    'parentId' : IDL.Principal,
  });
  const PendingRequestCompletedDetails = IDL.Record({
    'childPrincipal' : IDL.Principal,
    'childName' : IDL.Text,
    'successful' : IDL.Bool,
    'parent' : IDL.Principal,
  });
  const PhonePairingCompletedDetails = IDL.Record({
    'childId' : IDL.Principal,
    'parentId' : IDL.Principal,
  });
  const PairingDetails = IDL.Record({
    'child' : IDL.Principal,
    'parent' : IDL.Principal,
  });
  const AppRole = IDL.Variant({
    'admin' : IDL.Null,
    'child' : IDL.Null,
    'parent' : IDL.Null,
  });
  const AccountDeletedDetails = IDL.Record({
    'role' : AppRole,
    'account' : IDL.Principal,
  });
  const ContentCategory = IDL.Record({
    'name' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  const ContentFilterConfig = IDL.Record({
    'categories' : IDL.Vec(ContentCategory),
    'blocklist' : IDL.Vec(IDL.Text),
    'allowlist' : IDL.Vec(IDL.Text),
  });
  const FilterChangeDetails = IDL.Record({
    'child' : IDL.Principal,
    'newConfig' : ContentFilterConfig,
  });
  const AccountDisabledDetails = IDL.Record({
    'account' : IDL.Principal,
    'reason' : IDL.Text,
  });
  const DayTimeWindow = IDL.Record({
    'endHour' : IDL.Nat,
    'dayOfWeek' : IDL.Nat,
    'startHour' : IDL.Nat,
  });
  const ScheduleConfig = IDL.Record({
    'allowedHours' : IDL.Vec(DayTimeWindow),
    'dailyLimitMinutes' : IDL.Nat,
  });
  const ScheduleChangeDetails = IDL.Record({
    'child' : IDL.Principal,
    'newConfig' : ScheduleConfig,
  });
  const AuditLogDetails = IDL.Variant({
    'pendingRequestInitiated' : PendingRequestInitiatedDetails,
    'phonePairingInitiated' : PhonePairingInitiatedDetails,
    'pendingRequestCompleted' : PendingRequestCompletedDetails,
    'phonePairingCompleted' : PhonePairingCompletedDetails,
    'pairingCreated' : PairingDetails,
    'accountDeleted' : AccountDeletedDetails,
    'filterChanged' : FilterChangeDetails,
    'accountDisabled' : AccountDisabledDetails,
    'scheduleChanged' : ScheduleChangeDetails,
  });
  const AuditLogEntry = IDL.Record({
    'action' : ActionType,
    'timestamp' : Time,
    'details' : AuditLogDetails,
    'executor' : IDL.Principal,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : AppRole,
    'photo' : IDL.Opt(ExternalBlob),
    'phoneNumber' : IDL.Opt(IDL.Text),
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const PendingPairingRequest = IDL.Record({
    'id' : IDL.Nat,
    'pending' : IDL.Bool,
    'child' : IDL.Principal,
    'parent' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptPendingPairing' : IDL.Func([IDL.Nat], [PairWithParentResult], []),
    'addActivity' : IDL.Func([ActivityEntry], [], []),
    'addAllowlistedAdmin' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'addAllowlistedAdminPrincipal' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [],
        [],
      ),
    'addLocation' : IDL.Func([LocationEntry], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteCallerAccount' : IDL.Func([], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'generatePairingCode' : IDL.Func([], [IDL.Opt(IDL.Text)], []),
    'getActivities' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ActivityEntry)],
        ['query'],
      ),
    'getAdminDashboardMetrics' : IDL.Func(
        [],
        [AdminDashboardMetrics],
        ['query'],
      ),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getAllowlistedAdminPrincipals' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getAuditLog' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AuditLogEntry)],
        ['query'],
      ),
    'getCallerProfilePhoto' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContentFilter' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ContentFilterConfig)],
        ['query'],
      ),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getLiveLocationSharingStatus' : IDL.Func(
        [IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'getLocations' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(LocationEntry)],
        ['query'],
      ),
    'getMyChildren' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getMyParent' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getPendingPairingRequests' : IDL.Func(
        [],
        [IDL.Vec(PendingPairingRequest)],
        ['query'],
      ),
    'getSchedule' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ScheduleConfig)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAllowlistedAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPrincipalAllowlistedAdmin' : IDL.Func(
        [IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'pairWithParent' : IDL.Func([IDL.Text], [PairWithParentResult], []),
    'recordHeartbeat' : IDL.Func([], [], []),
    'removeAllowlistedAdminPrincipal' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [],
        [],
      ),
    'requestPairingWithParent' : IDL.Func(
        [IDL.Principal],
        [PairWithParentResult],
        [],
      ),
    'revokeAllowlistedAdmin' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProfilePhoto' : IDL.Func([ExternalBlob], [], []),
    'setLiveLocationSharing' : IDL.Func([IDL.Bool], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'updateContentFilter' : IDL.Func(
        [IDL.Principal, ContentFilterConfig],
        [],
        [],
      ),
    'updateSchedule' : IDL.Func([IDL.Principal, ScheduleConfig], [], []),
    'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };