/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountDeletedDetails {
  'role' : AppRole,
  'account' : Principal,
}
export interface AccountDisabledDetails {
  'account' : Principal,
  'reason' : string,
}
export type ActionType = { 'pendingRequestInitiated' : null } |
  { 'phonePairingInitiated' : null } |
  { 'pendingRequestCompleted' : null } |
  { 'phonePairingCompleted' : null } |
  { 'pairingCreated' : null } |
  { 'accountDeleted' : null } |
  { 'filterChanged' : null } |
  { 'accountDisabled' : null } |
  { 'scheduleChanged' : null };
export interface ActivityEntry {
  'appSite' : string,
  'childId' : Principal,
  'durationMinutes' : bigint,
  'notes' : string,
  'timestamp' : Time,
}
export interface AdminDashboardMetrics {
  'totalUsersEverLoggedIn' : bigint,
  'totalContentFiltersConfigured' : bigint,
  'totalSchedulesConfigured' : bigint,
  'activeSessionsEstimate' : bigint,
  'totalAdmins' : bigint,
  'totalPendingPairings' : bigint,
  'totalDisabledAccounts' : bigint,
  'totalParents' : bigint,
  'totalChildren' : bigint,
  'totalParentChildLinks' : bigint,
}
export type AppRole = { 'admin' : null } |
  { 'child' : null } |
  { 'parent' : null };
export type AuditLogDetails = {
    'pendingRequestInitiated' : PendingRequestInitiatedDetails
  } |
  { 'phonePairingInitiated' : PhonePairingInitiatedDetails } |
  { 'pendingRequestCompleted' : PendingRequestCompletedDetails } |
  { 'phonePairingCompleted' : PhonePairingCompletedDetails } |
  { 'pairingCreated' : PairingDetails } |
  { 'accountDeleted' : AccountDeletedDetails } |
  { 'filterChanged' : FilterChangeDetails } |
  { 'accountDisabled' : AccountDisabledDetails } |
  { 'scheduleChanged' : ScheduleChangeDetails };
export interface AuditLogEntry {
  'action' : ActionType,
  'timestamp' : Time,
  'details' : AuditLogDetails,
  'executor' : Principal,
}
export interface ContentCategory { 'name' : string, 'enabled' : boolean }
export interface ContentFilterConfig {
  'categories' : Array<ContentCategory>,
  'blocklist' : Array<string>,
  'allowlist' : Array<string>,
}
export interface DayTimeWindow {
  'endHour' : bigint,
  'dayOfWeek' : bigint,
  'startHour' : bigint,
}
export interface DeviceBatteryStatus {
  'timestamp' : Time,
  'batteryPercentage' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface FilterChangeDetails {
  'child' : Principal,
  'newConfig' : ContentFilterConfig,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface LocationEntry {
  'latitude' : number,
  'childId' : Principal,
  'longitude' : number,
  'timestamp' : Time,
}
export type PairWithParentResult = { 'alreadyUsed' : null } |
  { 'parentIdNotProvided' : null } |
  { 'phoneVerificationExpired' : null } |
  { 'notAChild' : null } |
  { 'codeExpired' : null } |
  { 'sameFamily' : null } |
  { 'unexpectedError' : null } |
  { 'phoneVerificationInitiated' : null } |
  { 'parentNotFound' : null } |
  { 'alreadyPaired' : null } |
  { 'parentNotParent' : null } |
  { 'pendingLinkRequest' : null } |
  { 'invalidCode' : null } |
  { 'phoneVerificationSuccess' : null } |
  { 'success' : null } |
  { 'phoneVerificationFailed' : null } |
  { 'phoneNumberAlreadyLinked' : null };
export interface PairingDetails { 'child' : Principal, 'parent' : Principal }
export interface PendingPairingRequest {
  'id' : bigint,
  'pending' : boolean,
  'child' : Principal,
  'parent' : Principal,
}
export interface PendingRequestCompletedDetails {
  'childPrincipal' : Principal,
  'childName' : string,
  'successful' : boolean,
  'parent' : Principal,
}
export interface PendingRequestInitiatedDetails {
  'child' : Principal,
  'parent' : Principal,
}
export interface PhonePairingCompletedDetails {
  'childId' : Principal,
  'parentId' : Principal,
}
export interface PhonePairingInitiatedDetails {
  'phoneNumber' : string,
  'parentId' : Principal,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface ScheduleChangeDetails {
  'child' : Principal,
  'newConfig' : ScheduleConfig,
}
export interface ScheduleConfig {
  'allowedHours' : Array<DayTimeWindow>,
  'dailyLimitMinutes' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : AppRole,
  'photo' : [] | [ExternalBlob],
  'phoneNumber' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptPendingPairing' : ActorMethod<[bigint], PairWithParentResult>,
  'addActivity' : ActorMethod<[ActivityEntry], undefined>,
  'addAllowlistedAdmin' : ActorMethod<[string, Principal], undefined>,
  'addAllowlistedAdminPrincipal' : ActorMethod<[string, Principal], undefined>,
  'addLocation' : ActorMethod<[LocationEntry], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeAdminPassword' : ActorMethod<[string, string], undefined>,
  'deleteCallerAccount' : ActorMethod<[], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'generatePairingCode' : ActorMethod<[], [] | [string]>,
  'getActivities' : ActorMethod<[Principal], Array<ActivityEntry>>,
  'getAdminDashboardMetrics' : ActorMethod<[], AdminDashboardMetrics>,
  'getAllDeviceBatteryStatuses' : ActorMethod<
    [],
    Array<[Principal, DeviceBatteryStatus]>
  >,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getAllowlistedAdminPrincipals' : ActorMethod<[], Array<Principal>>,
  'getAuditLog' : ActorMethod<[Principal], Array<AuditLogEntry>>,
  'getCallerProfilePhoto' : ActorMethod<[], [] | [ExternalBlob]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChildUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getChildUsersCount' : ActorMethod<[], bigint>,
  'getContentFilter' : ActorMethod<[Principal], [] | [ContentFilterConfig]>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getLiveLocationSharingStatus' : ActorMethod<[Principal], boolean>,
  'getLocations' : ActorMethod<[Principal], Array<LocationEntry>>,
  'getLoginCountByDay' : ActorMethod<[bigint, bigint, bigint], bigint>,
  'getLoginCountByMonth' : ActorMethod<[bigint, bigint], bigint>,
  'getLoginCountByYear' : ActorMethod<[bigint], bigint>,
  'getMyChildren' : ActorMethod<[], Array<Principal>>,
  'getMyParent' : ActorMethod<[], [] | [Principal]>,
  'getParentUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getParentUsersCount' : ActorMethod<[], bigint>,
  'getPendingPairingRequests' : ActorMethod<[], Array<PendingPairingRequest>>,
  'getSchedule' : ActorMethod<[Principal], [] | [ScheduleConfig]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerAllowlistedAdmin' : ActorMethod<[], boolean>,
  'isPrincipalAllowlistedAdmin' : ActorMethod<[Principal], boolean>,
  'pairWithParent' : ActorMethod<[string], PairWithParentResult>,
  'recordHeartbeat' : ActorMethod<[], undefined>,
  'recordLoginEvent' : ActorMethod<[string], undefined>,
  'removeAllowlistedAdminPrincipal' : ActorMethod<
    [string, Principal],
    undefined
  >,
  'requestPairingWithParent' : ActorMethod<[Principal], PairWithParentResult>,
  'revokeAllowlistedAdmin' : ActorMethod<[string, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProfilePhoto' : ActorMethod<[ExternalBlob], undefined>,
  'setLiveLocationSharing' : ActorMethod<[boolean], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'updateContentFilter' : ActorMethod<
    [Principal, ContentFilterConfig],
    undefined
  >,
  'updateDeviceBatteryStatus' : ActorMethod<[DeviceBatteryStatus], undefined>,
  'updateSchedule' : ActorMethod<[Principal, ScheduleConfig], undefined>,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];