/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
    role: AppRole;
    photo?: ExternalBlob;
    phoneNumber?: string;
}
export interface ScheduleChangeDetails {
    child: Principal;
    newConfig: ScheduleConfig;
}
export interface AccountDisabledDetails {
    account: Principal;
    reason: string;
}
export type Time = bigint;
export interface ScheduleConfig {
    allowedHours: Array<DayTimeWindow>;
    dailyLimitMinutes: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface InviteCode {
    created: Time;
    code: string;
    used: boolean;
}
export interface PendingPairingRequest {
    id: bigint;
    pending: boolean;
    child: Principal;
    parent: Principal;
}
export interface ContentCategory {
    name: string;
    enabled: boolean;
}
export interface PendingRequestCompletedDetails {
    childPrincipal: Principal;
    childName: string;
    successful: boolean;
    parent: Principal;
}
export interface PhonePairingInitiatedDetails {
    phoneNumber: string;
    parentId: Principal;
}
export interface DayTimeWindow {
    endHour: bigint;
    dayOfWeek: bigint;
    startHour: bigint;
}
export interface AccountDeletedDetails {
    role: AppRole;
    account: Principal;
}
export interface AuditLogEntry {
    action: ActionType;
    timestamp: Time;
    details: AuditLogDetails;
    executor: Principal;
}
export interface ContentFilterConfig {
    categories: Array<ContentCategory>;
    blocklist: Array<string>;
    allowlist: Array<string>;
}
export interface PendingRequestInitiatedDetails {
    child: Principal;
    parent: Principal;
}
export type AuditLogDetails = {
    __kind__: "pendingRequestInitiated";
    pendingRequestInitiated: PendingRequestInitiatedDetails;
} | {
    __kind__: "phonePairingInitiated";
    phonePairingInitiated: PhonePairingInitiatedDetails;
} | {
    __kind__: "pendingRequestCompleted";
    pendingRequestCompleted: PendingRequestCompletedDetails;
} | {
    __kind__: "phonePairingCompleted";
    phonePairingCompleted: PhonePairingCompletedDetails;
} | {
    __kind__: "pairingCreated";
    pairingCreated: PairingDetails;
} | {
    __kind__: "accountDeleted";
    accountDeleted: AccountDeletedDetails;
} | {
    __kind__: "filterChanged";
    filterChanged: FilterChangeDetails;
} | {
    __kind__: "accountDisabled";
    accountDisabled: AccountDisabledDetails;
} | {
    __kind__: "scheduleChanged";
    scheduleChanged: ScheduleChangeDetails;
};
export interface LocationEntry {
    latitude: number;
    childId: Principal;
    longitude: number;
    timestamp: Time;
}
export interface RSVP {
    name: string;
    inviteCode: string;
    timestamp: Time;
    attending: boolean;
}
export interface FilterChangeDetails {
    child: Principal;
    newConfig: ContentFilterConfig;
}
export interface AdminDashboardMetrics {
    totalUsersEverLoggedIn: bigint;
    totalContentFiltersConfigured: bigint;
    totalSchedulesConfigured: bigint;
    activeSessionsEstimate: bigint;
    totalAdmins: bigint;
    totalPendingPairings: bigint;
    totalDisabledAccounts: bigint;
    totalParents: bigint;
    totalChildren: bigint;
    totalParentChildLinks: bigint;
}
export interface ActivityEntry {
    appSite: string;
    childId: Principal;
    durationMinutes: bigint;
    notes: string;
    timestamp: Time;
}
export interface PairingDetails {
    child: Principal;
    parent: Principal;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface PhonePairingCompletedDetails {
    childId: Principal;
    parentId: Principal;
}
export enum ActionType {
    pendingRequestInitiated = "pendingRequestInitiated",
    phonePairingInitiated = "phonePairingInitiated",
    pendingRequestCompleted = "pendingRequestCompleted",
    phonePairingCompleted = "phonePairingCompleted",
    pairingCreated = "pairingCreated",
    accountDeleted = "accountDeleted",
    filterChanged = "filterChanged",
    accountDisabled = "accountDisabled",
    scheduleChanged = "scheduleChanged"
}
export enum AppRole {
    admin = "admin",
    child = "child",
    parent = "parent"
}
export enum PairWithParentResult {
    alreadyUsed = "alreadyUsed",
    parentIdNotProvided = "parentIdNotProvided",
    phoneVerificationExpired = "phoneVerificationExpired",
    notAChild = "notAChild",
    codeExpired = "codeExpired",
    sameFamily = "sameFamily",
    unexpectedError = "unexpectedError",
    phoneVerificationInitiated = "phoneVerificationInitiated",
    parentNotFound = "parentNotFound",
    alreadyPaired = "alreadyPaired",
    parentNotParent = "parentNotParent",
    pendingLinkRequest = "pendingLinkRequest",
    invalidCode = "invalidCode",
    phoneVerificationSuccess = "phoneVerificationSuccess",
    success = "success",
    phoneVerificationFailed = "phoneVerificationFailed",
    phoneNumberAlreadyLinked = "phoneNumberAlreadyLinked"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptPendingPairing(requestId: bigint): Promise<PairWithParentResult>;
    addActivity(entry: ActivityEntry): Promise<void>;
    addAllowlistedAdmin(adminPasswordAttempt: string, principal: Principal): Promise<void>;
    addAllowlistedAdminPrincipal(adminPasswordAttempt: string, principal: Principal): Promise<void>;
    addLocation(entry: LocationEntry): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    changeAdminPassword(oldPassword: string, newPassword: string): Promise<void>;
    deleteCallerAccount(): Promise<void>;
    generateInviteCode(): Promise<string>;
    generatePairingCode(): Promise<string | null>;
    getActivities(childId: Principal): Promise<Array<ActivityEntry>>;
    getAdminDashboardMetrics(): Promise<AdminDashboardMetrics>;
    getAllRSVPs(): Promise<Array<RSVP>>;
    getAllowlistedAdminPrincipals(): Promise<Array<Principal>>;
    getAuditLog(childId: Principal): Promise<Array<AuditLogEntry>>;
    getCallerProfilePhoto(): Promise<ExternalBlob | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContentFilter(childId: Principal): Promise<ContentFilterConfig | null>;
    getInviteCodes(): Promise<Array<InviteCode>>;
    getLiveLocationSharingStatus(childId: Principal): Promise<boolean>;
    getLocations(childId: Principal): Promise<Array<LocationEntry>>;
    getMyChildren(): Promise<Array<Principal>>;
    getMyParent(): Promise<Principal | null>;
    getPendingPairingRequests(): Promise<Array<PendingPairingRequest>>;
    getSchedule(childId: Principal): Promise<ScheduleConfig | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerAllowlistedAdmin(): Promise<boolean>;
    isPrincipalAllowlistedAdmin(principal: Principal): Promise<boolean>;
    pairWithParent(code: string): Promise<PairWithParentResult>;
    recordHeartbeat(): Promise<void>;
    removeAllowlistedAdminPrincipal(adminPasswordAttempt: string, principal: Principal): Promise<void>;
    requestPairingWithParent(parentId: Principal): Promise<PairWithParentResult>;
    revokeAllowlistedAdmin(adminPasswordAttempt: string, principal: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveProfilePhoto(blob: ExternalBlob): Promise<void>;
    setLiveLocationSharing(enabled: boolean): Promise<void>;
    submitRSVP(name: string, attending: boolean, inviteCode: string): Promise<void>;
    updateContentFilter(childId: Principal, newConfig: ContentFilterConfig): Promise<void>;
    updateSchedule(childId: Principal, newConfig: ScheduleConfig): Promise<void>;
    verifyAdminPassword(password: string): Promise<boolean>;
}
import type { AccountDeletedDetails as _AccountDeletedDetails, AccountDisabledDetails as _AccountDisabledDetails, ActionType as _ActionType, AppRole as _AppRole, AuditLogDetails as _AuditLogDetails, AuditLogEntry as _AuditLogEntry, ContentFilterConfig as _ContentFilterConfig, ExternalBlob as _ExternalBlob, FilterChangeDetails as _FilterChangeDetails, PairWithParentResult as _PairWithParentResult, PairingDetails as _PairingDetails, PendingRequestCompletedDetails as _PendingRequestCompletedDetails, PendingRequestInitiatedDetails as _PendingRequestInitiatedDetails, PhonePairingCompletedDetails as _PhonePairingCompletedDetails, PhonePairingInitiatedDetails as _PhonePairingInitiatedDetails, ScheduleChangeDetails as _ScheduleChangeDetails, ScheduleConfig as _ScheduleConfig, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptPendingPairing(arg0: bigint): Promise<PairWithParentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptPendingPairing(arg0);
                return from_candid_PairWithParentResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptPendingPairing(arg0);
            return from_candid_PairWithParentResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async addActivity(arg0: ActivityEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addActivity(arg0);
            return result;
        }
    }
    async addAllowlistedAdmin(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAllowlistedAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAllowlistedAdmin(arg0, arg1);
            return result;
        }
    }
    async addAllowlistedAdminPrincipal(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAllowlistedAdminPrincipal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAllowlistedAdminPrincipal(arg0, arg1);
            return result;
        }
    }
    async addLocation(arg0: LocationEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLocation(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async changeAdminPassword(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changeAdminPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeAdminPassword(arg0, arg1);
            return result;
        }
    }
    async deleteCallerAccount(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCallerAccount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCallerAccount();
            return result;
        }
    }
    async generateInviteCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteCode();
            return result;
        }
    }
    async generatePairingCode(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.generatePairingCode();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generatePairingCode();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivities(arg0: Principal): Promise<Array<ActivityEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivities(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivities(arg0);
            return result;
        }
    }
    async getAdminDashboardMetrics(): Promise<AdminDashboardMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminDashboardMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminDashboardMetrics();
            return result;
        }
    }
    async getAllRSVPs(): Promise<Array<RSVP>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRSVPs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRSVPs();
            return result;
        }
    }
    async getAllowlistedAdminPrincipals(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllowlistedAdminPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllowlistedAdminPrincipals();
            return result;
        }
    }
    async getAuditLog(arg0: Principal): Promise<Array<AuditLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLog(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLog(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerProfilePhoto(): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerProfilePhoto();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerProfilePhoto();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContentFilter(arg0: Principal): Promise<ContentFilterConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContentFilter(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContentFilter(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInviteCodes(): Promise<Array<InviteCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteCodes();
            return result;
        }
    }
    async getLiveLocationSharingStatus(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiveLocationSharingStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiveLocationSharingStatus(arg0);
            return result;
        }
    }
    async getLocations(arg0: Principal): Promise<Array<LocationEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocations(arg0);
            return result;
        }
    }
    async getMyChildren(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyChildren();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyChildren();
            return result;
        }
    }
    async getMyParent(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyParent();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyParent();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingPairingRequests(): Promise<Array<PendingPairingRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingPairingRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingPairingRequests();
            return result;
        }
    }
    async getSchedule(arg0: Principal): Promise<ScheduleConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSchedule(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSchedule(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerAllowlistedAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAllowlistedAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAllowlistedAdmin();
            return result;
        }
    }
    async isPrincipalAllowlistedAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isPrincipalAllowlistedAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isPrincipalAllowlistedAdmin(arg0);
            return result;
        }
    }
    async pairWithParent(arg0: string): Promise<PairWithParentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.pairWithParent(arg0);
                return from_candid_PairWithParentResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pairWithParent(arg0);
            return from_candid_PairWithParentResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordHeartbeat(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordHeartbeat();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordHeartbeat();
            return result;
        }
    }
    async removeAllowlistedAdminPrincipal(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAllowlistedAdminPrincipal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAllowlistedAdminPrincipal(arg0, arg1);
            return result;
        }
    }
    async requestPairingWithParent(arg0: Principal): Promise<PairWithParentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.requestPairingWithParent(arg0);
                return from_candid_PairWithParentResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestPairingWithParent(arg0);
            return from_candid_PairWithParentResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async revokeAllowlistedAdmin(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeAllowlistedAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeAllowlistedAdmin(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveProfilePhoto(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProfilePhoto(await to_candid_ExternalBlob_n38(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProfilePhoto(await to_candid_ExternalBlob_n38(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setLiveLocationSharing(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLiveLocationSharing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLiveLocationSharing(arg0);
            return result;
        }
    }
    async submitRSVP(arg0: string, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRSVP(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRSVP(arg0, arg1, arg2);
            return result;
        }
    }
    async updateContentFilter(arg0: Principal, arg1: ContentFilterConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContentFilter(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContentFilter(arg0, arg1);
            return result;
        }
    }
    async updateSchedule(arg0: Principal, arg1: ScheduleConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSchedule(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSchedule(arg0, arg1);
            return result;
        }
    }
    async verifyAdminPassword(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminPassword(arg0);
            return result;
        }
    }
}
function from_candid_AccountDeletedDetails_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountDeletedDetails): AccountDeletedDetails {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ActionType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActionType): ActionType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_AppRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_AuditLogDetails_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditLogDetails): AuditLogDetails {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_AuditLogEntry_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditLogEntry): AuditLogEntry {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_PairWithParentResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PairWithParentResult): PairWithParentResult {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContentFilterConfig]): ContentFilterConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ScheduleConfig]): ScheduleConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    action: _ActionType;
    timestamp: _Time;
    details: _AuditLogDetails;
    executor: Principal;
}): {
    action: ActionType;
    timestamp: Time;
    details: AuditLogDetails;
    executor: Principal;
} {
    return {
        action: from_candid_ActionType_n16(_uploadFile, _downloadFile, value.action),
        timestamp: value.timestamp,
        details: from_candid_AuditLogDetails_n18(_uploadFile, _downloadFile, value.details),
        executor: value.executor
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: _AppRole;
    account: Principal;
}): {
    role: AppRole;
    account: Principal;
} {
    return {
        role: from_candid_AppRole_n22(_uploadFile, _downloadFile, value.role),
        account: value.account
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _AppRole;
    photo: [] | [_ExternalBlob];
    phoneNumber: [] | [string];
}): Promise<{
    name: string;
    role: AppRole;
    photo?: ExternalBlob;
    phoneNumber?: string;
}> {
    return {
        name: value.name,
        role: from_candid_AppRole_n22(_uploadFile, _downloadFile, value.role),
        photo: record_opt_to_undefined(await from_candid_opt_n24(_uploadFile, _downloadFile, value.photo)),
        phoneNumber: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.phoneNumber))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingRequestInitiated: null;
} | {
    phonePairingInitiated: null;
} | {
    pendingRequestCompleted: null;
} | {
    phonePairingCompleted: null;
} | {
    pairingCreated: null;
} | {
    accountDeleted: null;
} | {
    filterChanged: null;
} | {
    accountDisabled: null;
} | {
    scheduleChanged: null;
}): ActionType {
    return "pendingRequestInitiated" in value ? ActionType.pendingRequestInitiated : "phonePairingInitiated" in value ? ActionType.phonePairingInitiated : "pendingRequestCompleted" in value ? ActionType.pendingRequestCompleted : "phonePairingCompleted" in value ? ActionType.phonePairingCompleted : "pairingCreated" in value ? ActionType.pairingCreated : "accountDeleted" in value ? ActionType.accountDeleted : "filterChanged" in value ? ActionType.filterChanged : "accountDisabled" in value ? ActionType.accountDisabled : "scheduleChanged" in value ? ActionType.scheduleChanged : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingRequestInitiated: _PendingRequestInitiatedDetails;
} | {
    phonePairingInitiated: _PhonePairingInitiatedDetails;
} | {
    pendingRequestCompleted: _PendingRequestCompletedDetails;
} | {
    phonePairingCompleted: _PhonePairingCompletedDetails;
} | {
    pairingCreated: _PairingDetails;
} | {
    accountDeleted: _AccountDeletedDetails;
} | {
    filterChanged: _FilterChangeDetails;
} | {
    accountDisabled: _AccountDisabledDetails;
} | {
    scheduleChanged: _ScheduleChangeDetails;
}): {
    __kind__: "pendingRequestInitiated";
    pendingRequestInitiated: PendingRequestInitiatedDetails;
} | {
    __kind__: "phonePairingInitiated";
    phonePairingInitiated: PhonePairingInitiatedDetails;
} | {
    __kind__: "pendingRequestCompleted";
    pendingRequestCompleted: PendingRequestCompletedDetails;
} | {
    __kind__: "phonePairingCompleted";
    phonePairingCompleted: PhonePairingCompletedDetails;
} | {
    __kind__: "pairingCreated";
    pairingCreated: PairingDetails;
} | {
    __kind__: "accountDeleted";
    accountDeleted: AccountDeletedDetails;
} | {
    __kind__: "filterChanged";
    filterChanged: FilterChangeDetails;
} | {
    __kind__: "accountDisabled";
    accountDisabled: AccountDisabledDetails;
} | {
    __kind__: "scheduleChanged";
    scheduleChanged: ScheduleChangeDetails;
} {
    return "pendingRequestInitiated" in value ? {
        __kind__: "pendingRequestInitiated",
        pendingRequestInitiated: value.pendingRequestInitiated
    } : "phonePairingInitiated" in value ? {
        __kind__: "phonePairingInitiated",
        phonePairingInitiated: value.phonePairingInitiated
    } : "pendingRequestCompleted" in value ? {
        __kind__: "pendingRequestCompleted",
        pendingRequestCompleted: value.pendingRequestCompleted
    } : "phonePairingCompleted" in value ? {
        __kind__: "phonePairingCompleted",
        phonePairingCompleted: value.phonePairingCompleted
    } : "pairingCreated" in value ? {
        __kind__: "pairingCreated",
        pairingCreated: value.pairingCreated
    } : "accountDeleted" in value ? {
        __kind__: "accountDeleted",
        accountDeleted: from_candid_AccountDeletedDetails_n20(_uploadFile, _downloadFile, value.accountDeleted)
    } : "filterChanged" in value ? {
        __kind__: "filterChanged",
        filterChanged: value.filterChanged
    } : "accountDisabled" in value ? {
        __kind__: "accountDisabled",
        accountDisabled: value.accountDisabled
    } : "scheduleChanged" in value ? {
        __kind__: "scheduleChanged",
        scheduleChanged: value.scheduleChanged
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    child: null;
} | {
    parent: null;
}): AppRole {
    return "admin" in value ? AppRole.admin : "child" in value ? AppRole.child : "parent" in value ? AppRole.parent : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    alreadyUsed: null;
} | {
    parentIdNotProvided: null;
} | {
    phoneVerificationExpired: null;
} | {
    notAChild: null;
} | {
    codeExpired: null;
} | {
    sameFamily: null;
} | {
    unexpectedError: null;
} | {
    phoneVerificationInitiated: null;
} | {
    parentNotFound: null;
} | {
    alreadyPaired: null;
} | {
    parentNotParent: null;
} | {
    pendingLinkRequest: null;
} | {
    invalidCode: null;
} | {
    phoneVerificationSuccess: null;
} | {
    success: null;
} | {
    phoneVerificationFailed: null;
} | {
    phoneNumberAlreadyLinked: null;
}): PairWithParentResult {
    return "alreadyUsed" in value ? PairWithParentResult.alreadyUsed : "parentIdNotProvided" in value ? PairWithParentResult.parentIdNotProvided : "phoneVerificationExpired" in value ? PairWithParentResult.phoneVerificationExpired : "notAChild" in value ? PairWithParentResult.notAChild : "codeExpired" in value ? PairWithParentResult.codeExpired : "sameFamily" in value ? PairWithParentResult.sameFamily : "unexpectedError" in value ? PairWithParentResult.unexpectedError : "phoneVerificationInitiated" in value ? PairWithParentResult.phoneVerificationInitiated : "parentNotFound" in value ? PairWithParentResult.parentNotFound : "alreadyPaired" in value ? PairWithParentResult.alreadyPaired : "parentNotParent" in value ? PairWithParentResult.parentNotParent : "pendingLinkRequest" in value ? PairWithParentResult.pendingLinkRequest : "invalidCode" in value ? PairWithParentResult.invalidCode : "phoneVerificationSuccess" in value ? PairWithParentResult.phoneVerificationSuccess : "success" in value ? PairWithParentResult.success : "phoneVerificationFailed" in value ? PairWithParentResult.phoneVerificationFailed : "phoneNumberAlreadyLinked" in value ? PairWithParentResult.phoneNumberAlreadyLinked : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AuditLogEntry>): Array<AuditLogEntry> {
    return value.map((x)=>from_candid_AuditLogEntry_n14(_uploadFile, _downloadFile, x));
}
function to_candid_AppRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: AppRole;
    photo?: ExternalBlob;
    phoneNumber?: string;
}): Promise<{
    name: string;
    role: _AppRole;
    photo: [] | [_ExternalBlob];
    phoneNumber: [] | [string];
}> {
    return {
        name: value.name,
        role: to_candid_AppRole_n36(_uploadFile, _downloadFile, value.role),
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n38(_uploadFile, _downloadFile, value.photo)) : candid_none(),
        phoneNumber: value.phoneNumber ? candid_some(value.phoneNumber) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    admin: null;
} | {
    child: null;
} | {
    parent: null;
} {
    return value == AppRole.admin ? {
        admin: null
    } : value == AppRole.child ? {
        child: null
    } : value == AppRole.parent ? {
        parent: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
